In [1]:
import numpy as np

In [3]:
#Wyznacznik macierzy:
A = np.array([[2,4], [-1, 3]])
round(np.linalg.det(A))

10

In [4]:
# Ślad macierzy - suma elementów macierzy na głównej przekątnej
np.trace(A)

5

In [5]:
# Macierz jednostkowa - macierz w której na głównej przekątnej są same jedynki, a reszta wypełniona
# Jest zerami

# Podajmy size oraz ewentualnie typ danych (domyślnie jest float)
np.eye(5, dtype='int')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [6]:
# Macierz odwrotna 



In [9]:
#Wyznaczamy macierz odwrotną:

B = np.linalg.inv(A)
B

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [11]:
np.set_printoptions(precision = 4, suppress = True)

# Sprawdzamy, czy pomnożenie macierzy przez macierz odwrotną daje macierz jednostkową:
np.dot(A, B)

array([[1., 0.],
       [0., 1.]])

In [13]:
# Macierz transponowana
A.T

array([[ 2, -1],
       [ 4,  3]])