In [1]:
import numpy as np

In [16]:
#Aby móc pomnożyć dwie macierze, liczba kolumn lewej macierzy musi się zgadzać z liczbą wierszy
# z prawej macierzy!!

A = np.arange(start = 1, stop = 21)
B = np.arange(start = 25, stop = 45)
A = A.reshape(5, -1)
B = B.reshape(-1, 5)
print(A)
print(B)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]]


In [24]:
Z = np.dot(A, B)
Z.shape

(5, 5)

In [29]:
X = np.array([[2,-1,3], [3,1,0]])
Y = np.array([[2,1,-1], [0,-1,2], [3,2,0]])
print(X, "\n")
print(Y)

[[ 2 -1  3]
 [ 3  1  0]] 

[[ 2  1 -1]
 [ 0 -1  2]
 [ 3  2  0]]


In [33]:
Z = np.dot(X, Y)
Z.shape

(2, 3)