In [1]:
import numpy as np

In [3]:
# Tworzenie tablicy o dowolnym rozmiarze z samych zer
A = np.zeros(shape = (4, 10))
print(A)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
# Automatycznie tworzą nam się dane o type float, mozemy zamienić na int

A = np.zeros(shape = (4, 10), dtype = 'int')
print(A)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [5]:
# Tworzenie tablicy o dowolnym rozmiarze z samymi jedynkami

B = np.ones(shape = (5, 10), dtype = 'int')
print(B)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [6]:
# Wypełnianie tablicy wartością, jaką my chcemy ją wypełnić

C = np.full(shape = (5, 5), fill_value = 4, dtype = 'int')
print(C)

[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]


In [7]:
# Generowanie tablic za pomocą funkcji np.arange

#Tablica z wartościami od 0 do 10, ale bez ostatniej wartości czyli 0-9
D = np.arange(10)
print(D)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
#Możemy również ustawić sobie od jakiej liczby do jakiej z jakim przeskokiem

E = np.arange(start = 8, stop = 29, step = 2)
print(E)

[ 8 10 12 14 16 18 20 22 24 26 28]


In [10]:
# Generowanie tablic za pomocą funkcji linspace

#Działanie funkcji linspace jest podobne do arange, tylko zamiast kroków podajemy ilość elementów
# jaka ma się znajdować w tablicy
F = np.linspace(start = 10, stop = 100, num = 10)
print(F)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [13]:
# Modyfikacja kształtu danych w tablicy za pomocą reshape()

G = np.arange(15)
print(G)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
#Zamiana rozmiaru
G.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
# Możemy również zrobić tak, aby python automatycznie rodzielił nam na równo wiersze lub kolumny
# Podając wartość -1.
#np chcemy mieć 3 wiersze i dodając wartość -1 do kolumn, python automaycznie wyliczy ilosc kolun

G.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
# I na odwrót:

G.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])