In [1]:
import numpy as np

In [3]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
# A[idx], A[start: stop], A[:stop], A[start:]

In [5]:
#Wycinamy 3 element
A[2]

2

In [6]:
# Od wartości 2 do końca
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [8]:
# Do wartości 2, ostatni index który podajemy nie wchodzi do tego przedziału
A[:2]

array([0, 1])

In [9]:
# Ostatni element
A[-1]

19

In [10]:
# Od 10 do 15 indeksu
A[10:15]

array([10, 11, 12, 13, 14])

In [11]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
# Wycięcie konkretnego wiersza:
A[0]

array([0, 1, 2, 3, 4])

In [15]:
# Wycięcie kolumny:
A[:, 0]
A[:, -1]

array([ 4,  9, 14, 19])

In [17]:
# Wycięcie onkretnego elemenu, np o wartości 6 A[wiersz, kolumna]
A[1,1]

6

In [19]:
# Wycięcie fragmentu, np: 6,7,8,11,12,13 A[]

A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [20]:
# Zamiana 7 na 14
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])