In [1]:
import numpy as np

In [4]:
#help(np.array)

In [7]:
# Stworzenie prostej tablicy jednowymiarowej (wektor)
x = np.array([1,3])
print(x)
type(x)

[1 3]


numpy.ndarray

In [12]:
#Atrybuty ndarray:

#Wymiar tablicy
print(x.ndim)

#Kształt tablicy
print(x.shape)

#Liczba elementów w tablicy
print(x.size)

#Typ danych
print(x.dtype)

1
(2,)
2
int32


In [15]:
# Stworzenie tablicy dwuwymiarowej:

y = np.array([[1,2], [-3,1]])
print(y)

[[ 1  2]
 [-3  1]]


In [16]:
#Wymiar tablicy
print(y.ndim)

#Kształt tablicy
print(y.shape)

#Liczba elementów w tablicy
print(y.size)

#Typ danych
print(y.dtype)

2
(2, 2)
4
int32


In [18]:
# tablica dwuwymiarowa o innym kształcie:

z = np.array([[1,2,4], [4,2,1]])
print(z)

[[1 2 4]
 [4 2 1]]


In [20]:
#Sprwdzamy kształt tablicy
z.shape

(2, 3)

In [21]:
#Tabice trójwymiarowe:

a = np.array(
    [[[4,3,1],
     [3, 1,2]],
     
     [[4,1,3],
     [4,2,1]]]
)
print(a)

[[[4 3 1]
  [3 1 2]]

 [[4 1 3]
  [4 2 1]]]


In [23]:
print(a.shape)

# 2 tablice, 2 wiersze i 3 kolumny

(2, 2, 3)
