In [4]:
import numpy as np

In [5]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [9]:
# Podstawowe działania arytmetyczne:
print(A + B)
print(A - B)
print(A * B)
print(A / B)

[6 0 7 4]
[0 2 1 0]
[ 9 -1 12  4]
[ 1.         -1.          1.33333333  1.        ]


In [11]:
# Można wykonać operację arytmetyczną za pomocą stałej do każdego elementu tablicy
A + 3
2 * A

array([6, 2, 8, 4])

In [14]:
# Biblioteka numpy posiada metody wbudowane do działań arytmetycznych
np.add(A, B)
np.subtract(A, B)
np.multiply(A, B)
np.divide(A, B)


array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [16]:
# Mnożenie macierzowe:

X = np.array([[1,3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [17]:
# Do wykonania mnożenia macierzowego służy metoda np.dot

np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [18]:
# Lub zamiast np.dot można uzyć @

X @ Y

array([[  3,   6],
       [-12,   0]])