In [1]:
import numpy as np

In [2]:
# ustawiamy ziarno losowania, aby za każdym razem uzyskiwać ten sam wynik losowania
np.random.seed(0)

In [5]:
# Losowa wartość z rozkładu normalnego
np.random.randn()

0.9787379841057392

In [7]:
# Tablica zawierająca x elementów losowych z rozkładu normalnego
np.random.randn(10)

array([ 2.2408932 ,  1.86755799, -0.97727788,  0.95008842, -0.15135721,
       -0.10321885,  0.4105985 ,  0.14404357,  1.45427351,  0.76103773])

In [8]:
# Tablica zawierająca x wierszy i y kolum elementów losowych z rozkładu normalnego
np.random.randn(10, 4)

array([[ 0.12167502,  0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575],
       [-1.98079647, -0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275, -1.04855297],
       [-1.42001794, -1.70627019,  1.9507754 , -0.50965218],
       [-0.4380743 , -1.25279536,  0.77749036, -1.61389785],
       [-0.21274028, -0.89546656,  0.3869025 , -0.51080514]])

In [9]:
# Losowa wartość z przedziału <0, 1)
np.random.rand()

0.8209932298479351

In [12]:
# Losowa liczba nieujmena mniejsza niż 10:
np.random.randint(10)

2

In [13]:
# Możemy ustawić wartość minimalną oraz maksymalną:
np.random.randint(low = 10, high = 101)

46

In [14]:
# Oraz można ustawić ilość wygenerowanych elementów, i wtedy storzymy tablice tych elementów
np.random.randint(low = 10, high = 101, size = 10)

array([44, 58, 13, 52, 87, 31, 83, 10, 20, 53])

In [15]:
# Możemy dokonać losowego wyboru z tablicy za pomocą np.random.choice

np.random.choice([1,4,5,6,10,20,50])

5

In [16]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Możemy przetasować nasze dane za pomocą funkcji shuffle
# Uruchomienie shuffle od razu zmienia dane w tablicy
np.random.shuffle(data)

In [18]:
data

array([9, 0, 6, 4, 5, 3, 8, 1, 2, 7])